name: main

on:
  push:
    paths-ignore:
      - 'examples/**'
  pull_request:
    paths-ignore:
      - 'examples/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go mod tidy
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test ./... -race -shuffle=on -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
